[build]
  publish = "dist/econet-frontend"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/angular-runtime"

# SPA fallback - handle all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200